// react-front/src/Produto.jsx
const Produto=({id,nome,desc,preco,imagem })=>{

    return(
        <>
        <div className="card">
        <img src={imagem} className="card-img-top img-fluid" alt="Imagem do Produto" />
        <div className="card-body">
          <h5 className="card-title">{nome}</h5>
          <p className="card-text">{desc}</p>
          <p className="card-text">Preço: R$ {preco}</p>
          <a href="#" className="btn btn-primary">Comprar</a>
        </div>
      </div>
      </>

    )
}

export default Produto;

// angular-front/src/app/produto/produto.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-produto',
  templateUrl: './produto.component.html',
  styleUrls: ['./produto.component.css']
})
export class ProdutoComponent {
  @Input() produto!: {id:number,nome:string,desc:string,preco:number,imagem:string};

}

<div class="card">
  <img src="{{produto.imagem}}" class="card-img-top img-fluid" alt="Imagem do Produto" >
  <div class="card-body">
    <h5 class="card-title">{{produto.nome}}</h5>
    <p class="card-text">{{produto.desc}}</p>
    <p class="card-text">Preço: R$ {{produto.preco}}</p>
    <a href="#" class="btn btn-primary">Comprar</a>
  </div>
</div>
